# coding: utf-8

"""
    Microsoft Bot Connector API - v3.0

    The Bot Connector REST API allows your bot to send and receive messages to channels configured in the  [Bot Framework Developer Portal](https://dev.botframework.com). The Connector service uses industry-standard REST  and JSON over HTTPS.    Client libraries for this REST API are available. See below for a list.    Many bots will use both the Bot Connector REST API and the associated [Bot State REST API](/en-us/restapi/state). The  Bot State REST API allows a bot to store and retrieve state associated with users and conversations.    Authentication for both the Bot Connector and Bot State REST APIs is accomplished with JWT Bearer tokens, and is  described in detail in the [Connector Authentication](/en-us/restapi/authentication) document.    # Client Libraries for the Bot Connector REST API    * [Bot Builder for C#](/en-us/csharp/builder/sdkreference/)  * [Bot Builder for Node.js](/en-us/node/builder/overview/)  * Generate your own from the [Connector API Swagger file](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json)    © 2016 Microsoft

    The version of the OpenAPI document: v3
    Contact: botframework@microsoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bot_connector.models.video_card import VideoCard

class TestVideoCard(unittest.TestCase):
    """VideoCard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VideoCard:
        """Test VideoCard
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VideoCard`
        """
        model = VideoCard()
        if include_optional:
            return VideoCard(
                title = '',
                subtitle = '',
                text = '',
                image = bot_connector.models.thumbnail_url.ThumbnailUrl(
                    url = '', 
                    alt = '', ),
                media = [
                    bot_connector.models.media_url.MediaUrl(
                        url = '', 
                        profile = '', )
                    ],
                buttons = [
                    bot_connector.models.card_action.CardAction(
                        type = 'openUrl', 
                        title = '', 
                        image = '', 
                        text = '', 
                        display_text = '', 
                        value = bot_connector.models.value.value(), 
                        channel_data = bot_connector.models.channel_data.channelData(), )
                    ],
                shareable = True,
                autoloop = True,
                autostart = True,
                aspect = '',
                duration = '',
                value = None
            )
        else:
            return VideoCard(
        )
        """

    def testVideoCard(self):
        """Test VideoCard"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
