# coding: utf-8

"""
    Microsoft Bot Connector API - v3.0

    The Bot Connector REST API allows your bot to send and receive messages to channels configured in the  [Bot Framework Developer Portal](https://dev.botframework.com). The Connector service uses industry-standard REST  and JSON over HTTPS.    Client libraries for this REST API are available. See below for a list.    Many bots will use both the Bot Connector REST API and the associated [Bot State REST API](/en-us/restapi/state). The  Bot State REST API allows a bot to store and retrieve state associated with users and conversations.    Authentication for both the Bot Connector and Bot State REST APIs is accomplished with JWT Bearer tokens, and is  described in detail in the [Connector Authentication](/en-us/restapi/authentication) document.    # Client Libraries for the Bot Connector REST API    * [Bot Builder for C#](/en-us/csharp/builder/sdkreference/)  * [Bot Builder for Node.js](/en-us/node/builder/overview/)  * Generate your own from the [Connector API Swagger file](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json)    © 2016 Microsoft

    The version of the OpenAPI document: v3
    Contact: botframework@microsoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bot_connector.models.payment_request_update import PaymentRequestUpdate

class TestPaymentRequestUpdate(unittest.TestCase):
    """PaymentRequestUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentRequestUpdate:
        """Test PaymentRequestUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentRequestUpdate`
        """
        model = PaymentRequestUpdate()
        if include_optional:
            return PaymentRequestUpdate(
                id = '',
                details = bot_connector.models.payment_details.PaymentDetails(
                    total = bot_connector.models.payment_item.PaymentItem(
                        label = '', 
                        amount = bot_connector.models.payment_currency_amount.PaymentCurrencyAmount(
                            currency = '', 
                            value = '', 
                            currency_system = '', ), 
                        pending = True, ), 
                    display_items = [
                        bot_connector.models.payment_item.PaymentItem(
                            label = '', 
                            pending = True, )
                        ], 
                    shipping_options = [
                        bot_connector.models.payment_shipping_option.PaymentShippingOption(
                            id = '', 
                            label = '', 
                            selected = True, )
                        ], 
                    modifiers = [
                        bot_connector.models.payment_details_modifier.PaymentDetailsModifier(
                            supported_methods = [
                                ''
                                ], 
                            additional_display_items = [
                                
                                ], 
                            data = bot_connector.models.data.data(), )
                        ], 
                    error = '', ),
                shipping_address = bot_connector.models.payment_address.PaymentAddress(
                    country = '', 
                    address_line = [
                        ''
                        ], 
                    region = '', 
                    city = '', 
                    dependent_locality = '', 
                    postal_code = '', 
                    sorting_code = '', 
                    language_code = '', 
                    organization = '', 
                    recipient = '', 
                    phone = '', ),
                shipping_option = ''
            )
        else:
            return PaymentRequestUpdate(
        )
        """

    def testPaymentRequestUpdate(self):
        """Test PaymentRequestUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
