# coding: utf-8

# flake8: noqa
"""
    Microsoft Bot Connector API - v3.0

    The Bot Connector REST API allows your bot to send and receive messages to channels configured in the  [Bot Framework Developer Portal](https://dev.botframework.com). The Connector service uses industry-standard REST  and JSON over HTTPS.    Client libraries for this REST API are available. See below for a list.    Many bots will use both the Bot Connector REST API and the associated [Bot State REST API](/en-us/restapi/state). The  Bot State REST API allows a bot to store and retrieve state associated with users and conversations.    Authentication for both the Bot Connector and Bot State REST APIs is accomplished with JWT Bearer tokens, and is  described in detail in the [Connector Authentication](/en-us/restapi/authentication) document.    # Client Libraries for the Bot Connector REST API    * [Bot Builder for C#](/en-us/csharp/builder/sdkreference/)  * [Bot Builder for Node.js](/en-us/node/builder/overview/)  * Generate your own from the [Connector API Swagger file](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json)    © 2016 Microsoft

    The version of the OpenAPI document: v3
    Contact: botframework@microsoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from bot_connector.models.action_types import ActionTypes
from bot_connector.models.activity import Activity
from bot_connector.models.activity_importance import ActivityImportance
from bot_connector.models.activity_types import ActivityTypes
from bot_connector.models.animation_card import AnimationCard
from bot_connector.models.attachment import Attachment
from bot_connector.models.attachment_data import AttachmentData
from bot_connector.models.attachment_info import AttachmentInfo
from bot_connector.models.attachment_layout_types import AttachmentLayoutTypes
from bot_connector.models.attachment_view import AttachmentView
from bot_connector.models.audio_card import AudioCard
from bot_connector.models.basic_card import BasicCard
from bot_connector.models.card_action import CardAction
from bot_connector.models.card_image import CardImage
from bot_connector.models.channel_account import ChannelAccount
from bot_connector.models.contact_relation_update_action_types import ContactRelationUpdateActionTypes
from bot_connector.models.conversation_account import ConversationAccount
from bot_connector.models.conversation_members import ConversationMembers
from bot_connector.models.conversation_parameters import ConversationParameters
from bot_connector.models.conversation_reference import ConversationReference
from bot_connector.models.conversation_resource_response import ConversationResourceResponse
from bot_connector.models.conversations_result import ConversationsResult
from bot_connector.models.delivery_modes import DeliveryModes
from bot_connector.models.end_of_conversation_codes import EndOfConversationCodes
from bot_connector.models.entity import Entity
from bot_connector.models.error import Error
from bot_connector.models.error_response import ErrorResponse
from bot_connector.models.fact import Fact
from bot_connector.models.geo_coordinates import GeoCoordinates
from bot_connector.models.hero_card import HeroCard
from bot_connector.models.inner_http_error import InnerHttpError
from bot_connector.models.input_hints import InputHints
from bot_connector.models.installation_update_action_types import InstallationUpdateActionTypes
from bot_connector.models.media_card import MediaCard
from bot_connector.models.media_event_value import MediaEventValue
from bot_connector.models.media_url import MediaUrl
from bot_connector.models.mention import Mention
from bot_connector.models.message_reaction import MessageReaction
from bot_connector.models.message_reaction_types import MessageReactionTypes
from bot_connector.models.microsoft_pay_method_data import MicrosoftPayMethodData
from bot_connector.models.o_auth_card import OAuthCard
from bot_connector.models.paged_members_result import PagedMembersResult
from bot_connector.models.payment_address import PaymentAddress
from bot_connector.models.payment_currency_amount import PaymentCurrencyAmount
from bot_connector.models.payment_details import PaymentDetails
from bot_connector.models.payment_details_modifier import PaymentDetailsModifier
from bot_connector.models.payment_item import PaymentItem
from bot_connector.models.payment_method_data import PaymentMethodData
from bot_connector.models.payment_options import PaymentOptions
from bot_connector.models.payment_request import PaymentRequest
from bot_connector.models.payment_request_complete import PaymentRequestComplete
from bot_connector.models.payment_request_complete_result import PaymentRequestCompleteResult
from bot_connector.models.payment_request_update import PaymentRequestUpdate
from bot_connector.models.payment_request_update_result import PaymentRequestUpdateResult
from bot_connector.models.payment_response import PaymentResponse
from bot_connector.models.payment_shipping_option import PaymentShippingOption
from bot_connector.models.place import Place
from bot_connector.models.receipt_card import ReceiptCard
from bot_connector.models.receipt_item import ReceiptItem
from bot_connector.models.resource_response import ResourceResponse
from bot_connector.models.role_types import RoleTypes
from bot_connector.models.semantic_action import SemanticAction
from bot_connector.models.semantic_action_states import SemanticActionStates
from bot_connector.models.signin_card import SigninCard
from bot_connector.models.suggested_actions import SuggestedActions
from bot_connector.models.text_format_types import TextFormatTypes
from bot_connector.models.text_highlight import TextHighlight
from bot_connector.models.thing import Thing
from bot_connector.models.thumbnail_card import ThumbnailCard
from bot_connector.models.thumbnail_url import ThumbnailUrl
from bot_connector.models.token_request import TokenRequest
from bot_connector.models.token_response import TokenResponse
from bot_connector.models.transcript import Transcript
from bot_connector.models.video_card import VideoCard
