# coding: utf-8

"""
    Microsoft Bot Connector API - v3.0

    The Bot Connector REST API allows your bot to send and receive messages to channels configured in the  [Bot Framework Developer Portal](https://dev.botframework.com). The Connector service uses industry-standard REST  and JSON over HTTPS.    Client libraries for this REST API are available. See below for a list.    Many bots will use both the Bot Connector REST API and the associated [Bot State REST API](/en-us/restapi/state). The  Bot State REST API allows a bot to store and retrieve state associated with users and conversations.    Authentication for both the Bot Connector and Bot State REST APIs is accomplished with JWT Bearer tokens, and is  described in detail in the [Connector Authentication](/en-us/restapi/authentication) document.    # Client Libraries for the Bot Connector REST API    * [Bot Builder for C#](/en-us/csharp/builder/sdkreference/)  * [Bot Builder for Node.js](/en-us/node/builder/overview/)  * Generate your own from the [Connector API Swagger file](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json)    © 2016 Microsoft

    The version of the OpenAPI document: v3
    Contact: botframework@microsoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from bot_connector.models.role_types import RoleTypes
from typing import Optional, Set
from typing_extensions import Self

class ConversationAccount(BaseModel):
    """
    Conversation account represents the identity of the conversation within a channel
    """ # noqa: E501
    is_group: Optional[StrictBool] = Field(default=None, description="Indicates whether the conversation contains more than two participants at the time the activity was generated", alias="isGroup")
    conversation_type: Optional[StrictStr] = Field(default=None, description="Indicates the type of the conversation in channels that distinguish between conversation types", alias="conversationType")
    tenant_id: Optional[StrictStr] = Field(default=None, description="This conversation's tenant ID", alias="tenantId")
    id: Optional[StrictStr] = Field(default=None, description="Channel id for the user or bot on this channel (Example: joe@smith.com, or @joesmith or 123456)")
    name: Optional[StrictStr] = Field(default=None, description="Display friendly name")
    aad_object_id: Optional[StrictStr] = Field(default=None, description="This account's object ID within Azure Active Directory (AAD)", alias="aadObjectId")
    role: Optional[RoleTypes] = None
    __properties: ClassVar[List[str]] = ["isGroup", "conversationType", "tenantId", "id", "name", "aadObjectId", "role"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConversationAccount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConversationAccount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "isGroup": obj.get("isGroup"),
            "conversationType": obj.get("conversationType"),
            "tenantId": obj.get("tenantId"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "aadObjectId": obj.get("aadObjectId"),
            "role": obj.get("role")
        })
        return _obj


