# coding: utf-8

"""
    Microsoft Bot Connector API - v3.0

    The Bot Connector REST API allows your bot to send and receive messages to channels configured in the  [Bot Framework Developer Portal](https://dev.botframework.com). The Connector service uses industry-standard REST  and JSON over HTTPS.    Client libraries for this REST API are available. See below for a list.    Many bots will use both the Bot Connector REST API and the associated [Bot State REST API](/en-us/restapi/state). The  Bot State REST API allows a bot to store and retrieve state associated with users and conversations.    Authentication for both the Bot Connector and Bot State REST APIs is accomplished with JWT Bearer tokens, and is  described in detail in the [Connector Authentication](/en-us/restapi/authentication) document.    # Client Libraries for the Bot Connector REST API    * [Bot Builder for C#](/en-us/csharp/builder/sdkreference/)  * [Bot Builder for Node.js](/en-us/node/builder/overview/)  * Generate your own from the [Connector API Swagger file](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json)    © 2016 Microsoft

    The version of the OpenAPI document: v3
    Contact: botframework@microsoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from bot_connector.models.activity import Activity
from bot_connector.models.channel_account import ChannelAccount
from typing import Optional, Set
from typing_extensions import Self

class ConversationParameters(BaseModel):
    """
    Parameters for creating a new conversation
    """ # noqa: E501
    is_group: Optional[StrictBool] = Field(default=None, description="IsGroup", alias="isGroup")
    bot: Optional[ChannelAccount] = None
    members: Optional[List[ChannelAccount]] = Field(default=None, description="Members to add to the conversation")
    topic_name: Optional[StrictStr] = Field(default=None, description="(Optional) Topic of the conversation (if supported by the channel)", alias="topicName")
    tenant_id: Optional[StrictStr] = Field(default=None, description="(Optional) The tenant ID in which the conversation should be created", alias="tenantId")
    activity: Optional[Activity] = None
    channel_data: Optional[Dict[str, Any]] = Field(default=None, description="Channel specific payload for creating the conversation", alias="channelData")
    __properties: ClassVar[List[str]] = ["isGroup", "bot", "members", "topicName", "tenantId", "activity", "channelData"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConversationParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of bot
        if self.bot:
            _dict['bot'] = self.bot.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in members (list)
        _items = []
        if self.members:
            for _item_members in self.members:
                if _item_members:
                    _items.append(_item_members.to_dict())
            _dict['members'] = _items
        # override the default output from pydantic by calling `to_dict()` of activity
        if self.activity:
            _dict['activity'] = self.activity.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConversationParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "isGroup": obj.get("isGroup"),
            "bot": ChannelAccount.from_dict(obj["bot"]) if obj.get("bot") is not None else None,
            "members": [ChannelAccount.from_dict(_item) for _item in obj["members"]] if obj.get("members") is not None else None,
            "topicName": obj.get("topicName"),
            "tenantId": obj.get("tenantId"),
            "activity": Activity.from_dict(obj["activity"]) if obj.get("activity") is not None else None,
            "channelData": obj.get("channelData")
        })
        return _obj


